blocks/footer/footer.js, blocks/header/header.js, scripts/lib-franklin.js, scripts/scripts.js, test/blocks/footer/footer.test.js, test/blocks/header/header.test.js
Implement language support.
Fix #1 
Test URLs:
- After: https://1-language-support--mammotome--hlxsites.hlx.page/en/
=> feat: language support

styles/styles.css
Set default section padding and max width
Test URLs:
- After: https://section-base-style-1--mammotome--hlxsites.hlx.page/en/
=> feat: section padding and max-width

blocks/cards/cards.js, scripts/lib-franklin.js
Prepare codebase for image optimization. Can be used by following features using images (e.g. image gallery).
Fix #34 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/dj-test
- After: https://31-ensure-optimized-picutures--mammotome--hlxsites.hlx.page/en/dj-test
=> feat: image optimization

blocks/hero/hero.css, scripts/scripts.js, styles/styles.css
Add hero styling.
Fix #23 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/dj-test
- After: https://23-hero-block--mammotome--hlxsites.hlx.page/en/dj-test
=> feat: hero block

blocks/carousel/carousel.js
Fix #48
Test URLs:
- After: https://48-image-carousel-not-starting-with-onload--mammotome--hlxsites.hlx.page/en/
=> fix: slide show auto-start

blocks/form/form.css, blocks/form/form.js, styles/styles.css
Fix #33 
Test URLs:
[Contact Us](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/) 
[Innovate Form](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/innovate-with-mammotome/)
[Study Request](https://33-forms--mammotome--hlxsites.hlx.page/en/contact/investigator-initiated-study-request/)
[Schedule Demo](https://33-forms--mammotome--hlxsites.hlx.page/en/schedule-a-demo/) 
[Tech Support Ticket](https://33-forms--mammotome--hlxsites.hlx.page/en/submit-a-tech-support-ticket/)
=> feat: form blocks

blocks/header/header.css, blocks/header/header.js
Fix #42 
Test URLs:
- After: https://42-site-search--mammotome--hlxsites.hlx.page/en/
=> feat: Site Search

blocks/header/header.css, blocks/header/header.js, scripts/delayed.js, scripts/lib-franklin.js
Fix #51 
Test URLs:
- After: https://51-i18n--mammotome--hlxsites.hlx.page/en/
=> feat: i18n placeholders

scripts/delayed.js
Fix #31 
Test URLs:
- After: https://31-cookieconstent--mammotome--hlxsites.hlx.page/en/
=> feat: Cookie Consent

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://fix-nav--mammotome--hlxsites.hlx.page/en/
=> fix: nav not showing when no subentries

blocks/header/header.js, scripts/delayed.js, scripts/lib-franklin.js
Fix #59 
Test URLs:
- After: https://59-global-i18n--mammotome--hlxsites.hlx.page/en/
=> feat: Global i18n and config

blocks/pdf-viewer/pdf-viewer.css, blocks/pdf-viewer/pdf-viewer.js, scripts/delayed.js, scripts/lib-franklin.js, scripts/scripts.js
Fix #28 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/dj-test-pdf-viewer
- After: https://28-pdf-flip-book--mammotome--hlxsites.hlx.page/en/dj-test-pdf-viewer
=> feat: pdf viewer

blocks/carousel/carousel.css
Fix #61 
Test URLs:
- After: https://61-image-carousel-alignment--mammotome--hlxsites.hlx.page/en/
=> fix: carousel vertical alignment

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Fix #45 
Test URLs:
- After: https://45-nav-follow-up--mammotome--hlxsites.hlx.page/en/
=> feat: Top Navigation - follow up

blocks/header/header.css, blocks/header/header.js
Fix #43 
Test URLs:
- After: https://43-contact-demo-buttons--mammotome--hlxsites.hlx.page/en/
=> add contact/demo button

helix-query.yaml
Test URLs:
- After: https://add-excludes-to-indexing--mammotome--hlxsites.hlx.page/en/
=> fix: exclude nav, footer and experiments from index

blocks/product-support/product-support.css, blocks/product-support/product-support.js, scripts/lib-franklin.js
Fix #72 
Test URLs:
Before: 
- https://main--mammotome--hlxsites.hlx.page/en/
After: 
- https://72-product-folders--mammotome--hlxsites.hlx.page/en/product-support/pc-1
- https://72-product-folders--mammotome--hlxsites.hlx.page/en/product-support/MM1
- https://72-product-folders--mammotome--hlxsites.hlx.page/en/product-support
=> feat: Folders based product pages

blocks/header/header.css, blocks/header/header.js
Fix #70 
Test URLs:
- After: https://70-collapse--mammotome--hlxsites.hlx.page/en/
=> feat: adding collapsible

blocks/ifus/ifus.js, blocks/product-list/product-list.css, blocks/product-list/product-list.js, blocks/product-support/product-support.js, scripts/lib-franklin.js
Fix #78 
Test URLs:
- After: https://78-product-list--mammotome--hlxsites.hlx.page/en/product-and-technical-documents
=> feat: Product List

blocks/footer/footer.css
Fix #85 
Test URLs:
- After: https://85-footer-column-alignment--mammotome--hlxsites.hlx.page/en/
=> footer columns align top #85

blocks/header/header.js, scripts/lib-franklin.js
Fix #16 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/
- After: https://16-language-navigation--mammotome--hlxsites.hlx.page/de/
=> language navigation (option 2)

blocks/header/header.css, blocks/hero/hero.css
Fix #97 
Test URLs:
- After: https://97-header-height-mismatch--mammotome--hlxsites.hlx.page/en/
=> change header nav height 85px to 90px

styles/styles.css
Fix #105 
Test URLs:
- After: https://105-overflow-hidden--mammotome--hlxsites.hlx.page/en/
=> bug: Vertical rubber band effect

blocks/tab-navigation/tab-navigation.css, blocks/tab-navigation/tab-navigation.js, scripts/lib-franklin.js, styles/styles.css
Fix #102 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/healthcare-professionals/seminars
- After: https://102-tab-block--mammotome--hlxsites.hlx.page/en/healthcare-professionals/seminars
=> feat: add Tab Block Navigation

blocks/product-reference/product-reference.css, blocks/product-reference/product-reference.js
Fix #93 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/products/mammotome-confirm
- After: https://93-product-ref--mammotome--hlxsites.hlx.page/en/products/mammotome-confirm
=> feat: Product-Support reference block

blocks/footer/footer.css, blocks/header/header.css, blocks/hero/hero.css, icons/logo.svg, styles/styles.css
Fix #107 
Test URLs:
- After: https://107-corp-logo-dimensions-change--mammotome--hlxsites.hlx.page/en/
=> change corp logo dimensions to 200x23 and fixed nav height

blocks/hero/hero.css, scripts/scripts.js
Fix #81
Test URLs:
- After: https://81-hero-follow-up--mammotome--hlxsites.hlx.page/en/
=> Hero image block follow-up

scripts/scripts.js
Fix #118 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/products/mammotome-confirm
- After: https://118-product-page-header--mammotome--hlxsites.hlx.page/en/products/mammotome-confirm
=> fix product header formatting with hero

blocks/header/header.css
Fix #120 
Test URLs:
- After: https://120-top-navigation-item-link-activation--mammotome--hlxsites.hlx.page/en/
=> fix nav link activation

blocks/header/header.css, styles/styles.css
…lts card in mobile view
Fix #104 
Test URLs:
- After: https://104-hidden-search-input-field--mammotome--hlxsites.hlx.page/en/
=> hidden search input field

blocks/header/header.css, styles/styles.css
Fix #123
Test URLs:
- After: https://123-align-search-aside--mammotome--hlxsites.hlx.page/en/
=> bug: align search aside with narrow nav

blocks/product-list/product-list.js, blocks/product-reference/product-reference.js, blocks/product-support/product-support.js, scripts/lib-franklin.js
Fix #128 
Test URLs:
Before: 
- https://main--mammotome--hlxsites.hlx.page/en/
After: 
- https://refactor-productdb--mammotome--hlxsites.hlx.page/en/products/mammotome-confirm
- https://refactor-productdb--mammotome--hlxsites.hlx.page/en/product-and-technical-documents
- https://refactor-productdb--mammotome--hlxsites.hlx.page/en/product-support/pc-1
=> cleanup: product lookup from productDB

blocks/carousel/carousel.css, blocks/carousel/carousel.js, styles/styles.css
Fix #132 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/products/bulletlist-image-test
- After: https://132-image-carousel-with-one-image--mammotome--hlxsites.hlx.page/en/products/bulletlist-image-test
=> Enhance Carousel for using it with one image

blocks/collapsible/collapsible.css, blocks/collapsible/collapsible.js
Implementation of #91
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/collapsible/collapsible
- After: https://91-collapsible--mammotome--hlxsites.hlx.page/en/collapsible/collapsible
=> feat: collapsible

blocks/product-list/product-list.css, blocks/product-list/product-list.js, blocks/product-reference/product-reference.css, blocks/product-reference/product-reference.js, blocks/product-support/product-support.css, blocks/product-support/product-support.js, scripts/lib-franklin.js
Fix #137 
Test URLs:
- After: https://137-optimized-picture--mammotome--hlxsites.hlx.page/en/product-support/4711
=> feat: usage createOptimizedPicture for productDB pictures

blocks/carousel/carousel.css
Fix #141 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/products/bulletlist-image-test
- After: https://141-image-carousel-image-alignment--mammotome--hlxsites.hlx.page/en/products/bulletlist-image-test
=> fix: image width in mobile view

blocks/header/header.css, blocks/header/header.js
Fix #139 
Test URLs:
- After: https://139-header-nav-improvement--mammotome--hlxsites.hlx.page/en/
=> fix: nav links on whole area

blocks/header/header.css
Fix #144 
Test URLs:
- After: https://144-no-header-jump--mammotome--hlxsites.hlx.page/en/
=> fix: header-nav entries jump on scroll

blocks/header/header.css
Fix #146 
Test URLs:
- After: https://146-vertical-distances-mobile-top-nav--mammotome--hlxsites.hlx.page/en/
=> fix vertical distances between nav sub menu

styles/styles.css
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/healthcare-professionals/webinars
- After: https://101-text-decoration--mammotome--hlxsites.hlx.page/en/healthcare-professionals/webinars
=> Add section style for default text

blocks/header/header.css, blocks/header/header.js, blocks/product-list/product-list.css, blocks/product-list/product-list.js, blocks/product-support/product-support.css, blocks/product-support/product-support.js, scripts/lib-franklin.js
Fix #164 
Test URLs:
- After: https://164-auto-sup--mammotome--hlxsites.hlx.page/en/
=> feat: Autosup trademark and registered signs in products

styles/styles.css
Fix #82
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/miroslav/contact-us
- After: https://82-contact-us--mammotome--hlxsites.hlx.page/en/miroslav/contact-us
=> 82 contact us

blocks/form/form.js
Fix #46
Test URLs:
https://46-attachments--mammotome--hlxsites.hlx.page/en/submit-a-tech-support-ticket/
=> Support of File upload and Google ReCaptcha integration

blocks/line/line.css, blocks/line/line.js
Fix: #177 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/patient-resources/breast-care
- After: https://177-horizontal-line--mammotome--hlxsites.hlx.page/en/patient-resources/breast-care
=> add horizontal line block

scripts/scripts.js, styles/styles.css
Fix #174
Test URLs:
- After: https://174-hero-overlap--mammotome--hlxsites.hlx.page/en/
=> feat: overlap with sections containing arc

scripts/lib-franklin.js
Fix #198 
Test URLs:
- After: https://198-fix-domexception--mammotome--hlxsites.hlx.page/en/
=> fix domexception when style contains empty string

fstab.yaml
Move mountpoint of content.
Test URLs:
- After: https://new-mountpoint--mammotome--hlxsites.hlx.page/en/
=> feat: update mountpoint to new location

.github/pull_request_template.md, fstab.yaml, scripts/lib-franklin.js
Test URLs:
- After: https://adjust-header--mammotome--hlxsites.hlx.page/us/en/
=> Adjust nav and footer lookup to country and language structure.

scripts/lib-franklin.js
Test URLs:
- After: https://rename-productdb--mammotome--hlxsites.hlx.page/us/en/
=> Rename product db

scripts/lib-franklin.js, styles/styles.css
Fix #205 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-care
- After: https://205-divider-block-gets-404--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-care
=> fix 404 on block divider

blocks/ifus/ifus.js
Fix #209 
Test URLs:
- After: https://209-revised-ifus--mammotome--hlxsites.hlx.page/us/en/
=> feat: add revisions to the eIFUs

blocks/header/header.js, blocks/ifus/ifus.js, scripts/lib-franklin.js
Test URLs:
- After: https://adjust-search-country--mammotome--hlxsites.hlx.page/us/en/
=> Adjust the search to the new country/language layout

blocks/cards/cards.css
Fix #212
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-biopsy
- After: https://212-cards-image-from-top--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-biopsy
=> fix: image block aspect ratio

blocks/header/header.js, blocks/ifus/ifus.js, blocks/product-list/product-list.js, blocks/product-reference/product-reference.js, blocks/product-support/product-support.js, scripts/lib-franklin.js
Test URLs:
- After: https://cleanup-productdb-info--mammotome--hlxsites.hlx.page/us/en/
=> Cleanup productdb info lookup

styles/styles.css
Fix #214
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/locations
- After: https://214-hero-overlays-text--mammotome--hlxsites.hlx.page/us/en/about-us/locations
=> fix: add relative positioning for sections

blocks/ifus/ifus.css, blocks/ifus/ifus.js
Test URLs:
- After: https://adjust-ifus-style--mammotome--hlxsites.hlx.page/us/en/ifu-index
=> Adjust the ifus block to the new styles

blocks/ifus/ifus.css, blocks/product-support/product-support.css, blocks/product-support/product-support.js
Test URLs:
- After: https://adjust-product-support-styles--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-elite-support
=> Adjust product support styles

styles/styles.css
Fix #226 
Test URLs:
- After: https://226-inverted-text-with-overlays--mammotome--hlxsites.hlx.page/us/en/
=> add inverted text section style

styles/styles.css
Fix #223
Test URLs:
- After: https://223-callout-improvement--mammotome--hlxsites.hlx.page/us/en/
=> fix: heading font size and section padding

helix-query.yaml, helix-sitemap.yaml, robots.txt
Fix #172 
Test URLs:
- After: https://update-indexing-sitemap-country-lang--mammotome--hlxsites.hlx.page/us/en/
=> fix: adjust to new country/language structure

styles/styles.css
Fix #229
Test URLs:
- After: https://229-z-index-workaround--mammotome--hlxsites.hlx.page/us/en/
=> bug: workaround negative z-index used in overlapping sections

blocks/columns/columns.css, blocks/columns/columns.js
Fix #231 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/mri
- After: https://231-header-flows-into-hero-arc-picture--mammotome--hlxsites.hlx.page/us/en/portfolios/mri
=> fix header flow over hero arc

scripts/scripts.js, styles/styles.css
Fix #238 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
- After: https://238-hero-light-text-overflow--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
=> Fix hero light text overflow

blocks/collapsible/collapsible.css
Fix #237
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
- After: https://237-collapsible-text-alignement--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
=> fix: text alignement

blocks/cards/cards.css, blocks/cards/cards.js
Fix #235
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/miroslav/cards-test
- After: https://235-cards-styles-enhancements--mammotome--hlxsites.hlx.page/us/en/miroslav/cards-test
=> feat: style enhancements

blocks/hero/hero.css, scripts/scripts.js
Fix #183 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
- After: https://183-Hero-image-overlay--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
=> Hero image overlay

blocks/cards/cards.css
Fix #243 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media
- After: https://243-fix-fullimage-cards--mammotome--hlxsites.hlx.page/us/en/about-us/news-media
=> fix: card image size

styles/styles.css
Fix #251
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/
- After: https://251-missing-rectangle--mammotome--hlxsites.hlx.page/us/en/about-us/
=> Missing blue rectangle in Columns Block

scripts/scripts.js, scripts/third-party.js
See #216 
Test URLs:
- After: https://inline-martec--mammotome--hlxsites.hlx.page/us/en/
=> Inline integrateMartech

blocks/columns/columns.css, blocks/columns/columns.js
Fix #248 
Test URLs:
- After: https://248-fix-bottom-padding--mammotome--hlxsites.hlx.page/us/en/
=> fix: padding

blocks/cards/cards.js
Fix #257 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/legal/terms-conditions
- After: https://bug-257-icons-on-headings--mammotome--hlxsites.hlx.page/us/en/legal/terms-conditions
=> 257 - don't show icons on headings inside cards block

styles/styles.css
Fix #266
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
- After: https://266-callout-padding--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
=> fix: callout padding

blocks/columns/columns.css
Fix #276
Test URLs:
- After: https://276-card-image-padding--mammotome--hlxsites.hlx.page/us/en/
=> fix: remove left and right padding

blocks/header/header.css
Fix #287 
Test URLs:
- After: https://287-adjust-font-size-for-search-bar--mammotome--hlxsites.hlx.page/us/en/
=> adjust font size and height for search bar

scripts/lib-franklin.js, styles/styles.css
Add Section Style `spacer` in Word first. 
Fix #245 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
- After: https://245-add-flexible-spacer-as-section-style--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
=> Add Section Style SPACER

styles/styles.css
Fix #245 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm
- After: https://Improve-flexible-spacer--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm
=> Improve Flex Spacer from #245

blocks/carousel/carousel.css, styles/styles.css
Fix #278 
Test URLs:
- Before: 
- https://main--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm
- https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- After: 
- https://278-ul-bullets-to-plain-bullets--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm
- https://278-ul-bullets-to-plain-bullets--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
=> Change colored list style to default list style

styles/styles.css
Fix #284
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
- After: https://284-callout-mobile-text--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
=> fix: callout font size for mobile

blocks/columns/columns.css
Fix #298
Test URLs:
- After: https://298-cards-block-image-layout--mammotome--hlxsites.hlx.page/us/en/
=> fix: paragraph with image layout

fstab.yaml
Test URLs:
- After: https://product-support-it--mammotome--hlxsites.hlx.page/us/en/
=> Add product support folders for all languages

blocks/hero/hero.css
Fix #282
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
- After: https://282-arc-safari-issue--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
=> fix: move arc 1px

blocks/columns/columns.css
Fix #291
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence
- After: https://bug-291-registered-marks--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence
=> 291 - Change superscript font size and position in columns block with links

scripts/lib-franklin.js
Fix #308 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/mammogram-guidelines
- After: https://308-pdf-links--mammotome--hlxsites.hlx.page/us/en/patient-resources/mammogram-guidelines
=> fix: pdf links

blocks/columns/columns.css, styles/styles.css
Fix #305
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
- After: https://305-column-enhancement--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
=> fix: image padding, link color invert

blocks/collapsible/collapsible.css, blocks/prev-next/prev-next.css, blocks/prev-next/prev-next.js, styles/styles.css
Fix #315 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
- After: https://315-collapsible-alignment--mammotome--hlxsites.hlx.page/us/en/patient-resources/faq-about-the-devices
=> Collapsible alignment issue

blocks/columns/columns.css
Fix #285 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-sentinel-lymph-node-biopsy
- After: https://285-column-mobile-padding--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-sentinel-lymph-node-biopsy
=> Fix Column mobile padding

tools/importer/import.js
Test URLs:
- After: https://cards-columns--mammotome--hlxsites.hlx.page/us/en/
=> identify number of columns for cards

tools/importer/import.js
Test URLs:
- After: https://import-video--mammotome--hlxsites.hlx.page/us/en/
test page(s) for import https://it.mammotome.com/products/mammotome-revolve/mammotome-revolve-u-s/
https://it.mammotome.com/products/mammotome-elite/
soundcloud page https://www.mammotome.com/news-media/mammotome-one-voice/
=> import of video block & sound cloud block

styles/styles.css
Fix #336 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/hospital-marketing-kit-preview
- After: https://336-paragraph-line-heights--mammotome--hlxsites.hlx.page/us/en/hospital-marketing-kit-preview
=> Paragraph line-height for default text

blocks/columns/columns.css, styles/styles.css
Fix #323
Test URLs:
- Before 1: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- After 1: https://305-column-enhancement--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- Before 2: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
- After 2: https://305-column-enhancement--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
=> 305 column enhancement

tools/importer/import.js
use https://www.mammotome.com/patient-resources/faqs-about-the-devices/
Test URLs:
- After: https://collapsible--mammotome--hlxsites.hlx.page/us/en/
=> collapsible block

blocks/form/form.css, blocks/form/form.js
Fix #313 #311 
Test URLs:
- After: https://313-mammotomoe--mammotome--hlxsites.hlx.page/us/en/
=> error: Text error message for non 200 form submission

blocks/cards/cards.css
Fix #277 
Fix #294 
Test URLs:
- After: https://277-cards-margin--mammotome--hlxsites.hlx.page/us/en/
=> 277 & 294 – Fix card margin and gap

tools/importer/import.js
use https://www.mammotome.com/patient-resources/faqs-about-the-device
https://www.mammotome.com/patient-resources/mammotome-breast-biopsy-devices/
Test URLs:
- After: https://prevnext--mammotome--hlxsites.hlx.page/us/en/
=> import of prev-next block

blocks/columns/columns.css
Fix #353 
Test URLs:
- After: https://353-columns-margin--mammotome--hlxsites.hlx.page/us/en/
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- After: https://353-columns-margin--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
=> fix: margins in columns

blocks/cards/cards.css
Fix #350 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/products/
- After: https://350-fix-cards-img--mammotome--hlxsites.hlx.page/us/en/products/
=> fix: image in cards

blocks/columns/columns.js, docs/blocks/columns.md, styles/styles.css
…for logo backgrounds
Fix #322 
Test URLs:
- After: https://322-clickable-cards--mammotome--hlxsites.hlx.page/us/en/
=> Clickable Images for Columns block

blocks/form/form.css
Test URLs:
- After: https://namecss--mammotome--hlxsites.hlx.page/us/en/contact/
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- After: https://namecss--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/investigator-initiated-study-request
- After: https://namecss--mammotome--hlxsites.hlx.page/us/en/about-us/investigator-initiated-study-request
@review @neerajadobe93
=> fix: Adjust form field css based on changed name

docs/blocks/cards.md
Fix #357
Test URLs:
- After: https://357-cards-ducumentation--mammotome--hlxsites.hlx.page/us/en/
=> feat: doc for cards block

blocks/columns/columns.css, blocks/columns/columns.js, docs/blocks/columns.md
Fix #364 
Test URLs:
- After: https://364-follow-up-on-clickable-images--mammotome--hlxsites.hlx.page/us/en/
=> bug fixes in js and fixed h3 font-size

blocks/columns/columns.css
Fix #367 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/careers-blog
- After: https://367-fix-heading-style--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/careers-blog
=> fix: Link style overrides heading style in columns

blocks/form/file.js, blocks/form/form.js
Test URLs:
https://main--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers
=> @trivial updating thank you page URL

styles/styles.css
Fix #370 
Test URLs:
- After: https://370-callout-font-size-alignment--mammotome--hlxsites.hlx.page/us/en/
=> Align callout header sizes

styles/styles.css
Fix #373
Test URLs:
- After: https://373-font-weight-logo-background--mammotome--hlxsites.hlx.page/us/en/
=> Fix callout logo background font-size

helix-query.yaml
Test URLs:
- After: https://index--mammotome--hlxsites.hlx.page/us/en/
=> fix: query index for us/en

blocks/columns/columns.css, styles/styles.css
Fix #375
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/careers-blog-aspire-to-inspire
- After: https://375-fix-column-background--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/careers-blog-aspire-to-inspire
=> fix: column background

blocks/header/header.js
Fix #380 
Test URLs:
- After: https://380-seo-nav-overflow-button--mammotome--hlxsites.hlx.page/us/en/
=> fix: nav-overflow button SEO

blocks/footer/footer.css, blocks/header/header.js, scripts/lib-franklin.js
Fix #382 
Test URLs:
- After: https://382-accessibility-header-footer-icons--mammotome--hlxsites.hlx.page/us/en/
=> fix: add aria-label / title for linked svg

blocks/footer/footer.js
Fix #384 
Test URLs:
- After: https://384-cookie-settings--mammotome--hlxsites.hlx.page/us/en/
=> feat: support cookie settings

blocks/columns/columns.css, docs/section-metadata.md, styles/styles.css
Fix #385 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/dj-test
- After: https://385-fix-bottom-arc--mammotome--hlxsites.hlx.page/us/en/dj-test
=> 385 fix bottom arc

blocks/cards/cards.css, blocks/cards/cards.js, docs/blocks/cards.md, styles/styles.css
Fix #377 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/cards-column-test
- After: https://377-two-column-cards--mammotome--hlxsites.hlx.page/us/en/cards-column-test
=> feat: two columns cards

blocks/carousel/carousel.js, blocks/product-reference/product-reference.js
Collection PR for various accessibility fixes.
Test URLs:
- After: https://accessibility-fixes--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
=> Accessibility fixes

blocks/product-support/product-support.css, blocks/product-support/product-support.js, blocks/video/video.js
Fix #388 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/product-support/neoprobe-gamma-detection-system
- After: https://388-product-support-video--mammotome--hlxsites.hlx.page/us/en/product-support/neoprobe-gamma-detection-system
=> Add support for videos in product support

blocks/footer/footer.css
Fix #400
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/it/it/
- After: https://400-footer-headers-padding--mammotome--hlxsites.hlx.page/it/it/
=> increase footer header margin

blocks/columns/columns.css, blocks/header/header.css, blocks/hero/hero.css, styles/styles.css
Fix #232 
Test URLs:
- After: https://232-stacking-context--mammotome--hlxsites.hlx.page/us/en/
=> Remove z-index workaround

docs/section-metadata.md, styles/styles.css
Fix #404 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-revolve/
- After: https://404-add-section-style-text-uppercase--mammotome--hlxsites.hlx.page/de/de/products/mammotome-revolve/
=> add text-uppercase and add to doc

blocks/ifus/ifus.js, blocks/product-reference/product-reference.js
Fix #402 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-confirm
- After: https://402-translate--mammotome--hlxsites.hlx.page/de/de/products/mammotome-confirm
=> fix: translate keys correctly

blocks/form/form.css, blocks/form/form.js, blocks/form/wizard.js
Fix #340 
Test URLs:
- After: https://wizard--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
@review @vdua
=> feat(form): wizard implementation

blocks/video/video.css, blocks/video/video.js, docs/blocks/video.md
Fix #98 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/stereotactic
- After: https://98-video-player-bug--mammotome--hlxsites.hlx.page/us/en/portfolios/stereotactic
=> fix: video player follow up

blocks/carousel/carousel.css, docs/blocks/carousel.md
Fix #410 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/hydromark
- After: https://410-add-narrow-attribute-for-carousel--mammotome--hlxsites.hlx.page/de/de/products/mammotome-brustbiopsiemarker/hydromark
=> add narrow option

blocks/carousel/carousel.css
Fix #413 
Test URLs:
- After: https://413-change-object-fit-in-carousel--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
=> change object-fit

scripts/lib-franklin.js
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/uk/en/
- After: https://fix-uk-gb--mammotome--hlxsites.hlx.page/uk/en/
=> fix: the country code for en-gb is uk

blocks/columns/columns.css, blocks/columns/columns.js
Fix #415 
Test URLs:
- After: https://415-fix-image-cards--mammotome--hlxsites.hlx.page/us/en/
=> fix: HCP/Patient Resources Buttons: Image Cards

scripts/scripts.js
Fix #64 
Test URLs:
- After: https://64-styled-sections--mammotome--hlxsites.hlx.page/us/en/
=> feat: background-image optimization

blocks/video/video.css
Fix #423 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/stereotactic
- After: https://423-video-padding--mammotome--hlxsites.hlx.page/us/en/portfolios/stereotactic
=> Remove bottom video padding

styles/styles.css
Fix #428 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/our-history
- After: https://428-calendar-icon--mammotome--hlxsites.hlx.page/us/en/about-us/our-history
=> Our History: Calendar Icon fix

blocks/collapsible/collapsible.js
Fix #433 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/uk/en/product-support
- After: https://433-collapsible-formatting--mammotome--hlxsites.hlx.page/uk/en/product-support
=> fix: collapsible link formatting

blocks/form/form.css, blocks/form/form.js, blocks/form/utm.js
Fix #342
Test URLs:
- After: https://342-mammotome--mammotome--hlxsites.hlx.page/us/en/contact/
- After: https://342-mammotome--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- After: https://342-mammotome--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
=> Hidden fields for forms

blocks/header/header.js, docs/section-metadata.md
Fix #441 
Test URLs:
- After: https://441-nav-buttons--mammotome--hlxsites.hlx.page/us/en/
=> Improve nav buttons

blocks/header/header.js
Fix #450 
Test URLs:
- After: https://450-fix-mobile-nav--mammotome--hlxsites.hlx.page/us/en/
=> fix: top level mobile nav

scripts/lib-franklin.js
Fix #452 
Test URLs:
- After: https://452-products-nav-active-link-highlight--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/
=> fix products-nav highlighting for URL ending with /

blocks/collapsible/collapsible.css, blocks/collapsible/collapsible.js
Fix #455 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/product-support
- After: https://455-superscript-collapsible--mammotome--hlxsites.hlx.page/de/de/product-support
=> fix supscript in collapsible

blocks/form/form.js
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/es/es/contacto
- After: https://form-subscript--mammotome--hlxsites.hlx.page/es/es/contacto
=> fix: forms block should decorate the supscript

styles/styles.css
Fix #424 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/products/
- After: https://424-sup-styling--mammotome--hlxsites.hlx.page/us/en/products/
=> Sup css styling

blocks/columns/columns.css
Fix #448 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/es/es/products/tru-core-ii
- After: https://448-align-self--mammotome--hlxsites.hlx.page/es/es/products/tru-core-ii
=> Align columns

blocks/columns/columns.css
Test URLs:
- After: https://448-align-self--mammotome--hlxsites.hlx.page/us/en/
=> Only align columns if column is set to centered

docs/section-metadata.md, styles/styles.css
Fix #462 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/technical-support
- After: https://462-metadata-request--mammotome--hlxsites.hlx.page/us/en/technical-support
=> add Style Metadata option: header-colored-secondary

blocks/video/video.css
Fix #449 
Test URLs:
- After: https://449-video-spacing--mammotome--hlxsites.hlx.page/us/en/
=> fix: video container top/bottom spacing

blocks/columns/columns.css, styles/styles.css
Fix #461 
Test URLs:
- After: https://461-link-colors--mammotome--hlxsites.hlx.page/us/en/
=> fix: set default link color to blue

scripts/lib-franklin.js
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support
- After: https://button-sup--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support
=> fix: sup styling in buttons

blocks/product-support/product-support.css
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support
- After: https://product-support-header--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support
=> Adjust size of product support header to look like h4

blocks/form/form.css, blocks/form/form.js, blocks/form/utm.js
Fix #458 #438 #426 #437 
Test URLs:
Before: https://main--mammotome--hlxsites.hlx.page/us/en/contact/
After: https://formbug2--mammotome--hlxsites.hlx.page/us/en/contact/
Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
After: https://formbug2--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
Before: https://main--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
After: https://formbug2--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
After: https://formbug2--mammotome--hlxsites.hlx.page/us/en/about-us/ …
=> fix(bug): fix form bug raised by customer

blocks/form/form.js
Fix #472 #476 
Test URLs:
Before: https://main--mammotome--hlxsites.hlx.page/us/en/contact/
After: https://formbug3--mammotome--hlxsites.hlx.page/us/en/contact/
Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
After: https://formbug3--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
Before: https://main--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
After: https://formbug3--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
After: https://formbug3--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-w …
=> fix(bug): Add placeholder option and current date while form submission

blocks/form/form.js
Test URLs:
- After: https://formbug4--mammotome--hlxsites.hlx.page/us/en/contact/
=> fix: change format of 'Last Form Date' to 'MM/DD/YYYY'

blocks/form/form.js
=> @trivial updated google site key

blocks/form/form.css
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.live/us/en/contact/
- After: https://products--mammotome--hlxsites.hlx.live/us/en/contact/
- Before: https://main--mammotome--hlxsites.hlx.live/fr/fr/contact
- After: https://products--mammotome--hlxsites.hlx.live/fr/fr/contact
- Before: https://main--mammotome--hlxsites.hlx.live/de/de/kontakt
- After: https://products--mammotome--hlxsites.hlx.live/de/de/kontakt
- Before: https://main--mammotome--hlxsites.hlx.live/es/es/contacto
- After: https://products--mammotome--hlxsites.hlx.live/es/es/contacto
- Before: https://main--mammotome--hlxsites.hlx.live/pl/pl/kontakt
- …
=> fix: Correct the product width when two column

blocks/form/form.js
Test URLs:
- After: https://contact--mammotome--hlxsites.hlx.page/us/en/contact/
=> fix: update form url to new metadata

blocks/carousel/carousel.css, blocks/prev-next/prev-next.css
…lated to the issue)
Fix #487
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-cancer-myths
- After: https://487-prevnext-not-appearing-on-mobile--mammotome--hlxsites.hlx.page/us/en/patient-resources/breast-cancer-myths
=> Fix prev-next not appearing on Safari

blocks/header/header.css
Open search and search for e.g. "confirm" 
Fix #489 
Test URLs:
- After: https://489-search-results-text-alignment-and-sup--mammotome--hlxsites.hlx.page/us/en/
=> fix text and sup alignment in search

blocks/columns/columns.js, blocks/header/header.css, blocks/header/header.js, blocks/video/video.css, styles/styles.css
Fix #499 
Test URLs:
- After: https://499-firefox-issue--mammotome--hlxsites.hlx.page/us/en/
=> fix: replace :has selector

blocks/cards/cards.css, blocks/collapsible/collapsible.css, blocks/columns/columns.css, blocks/hero/hero.css, docs/section-metadata.md, scripts/scripts.js, styles/styles.css
Fix #504 
Test URLs:
- After: https://504-chore-remove-all-arcs--mammotome--hlxsites.hlx.page/us/en/
=> chore: remove all arcs

blocks/footer/footer.css
Fix #497 
Test URLs:
- After: https://497-restyle-footer-fix-01--mammotome--hlxsites.hlx.page/us/en/
=> fix: text align footer heading

blocks/cards/cards.css, blocks/form/form.css, blocks/form/form.js, blocks/header/header.css, blocks/header/header.js, scripts/lib-franklin.js, styles/styles.css
Fix #507 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/dj-test/en/
- After: https://507-feat-header-style-update--mammotome--hlxsites.hlx.page/dj-test/en/
=> feat: header style update

blocks/header/header.css, blocks/header/header.js
Fix #513 
Test URLs:
- After: https://513-search-icon-hamburger-overlap--mammotome--hlxsites.hlx.page/us/en/
=> fix: optimize nav search icon placement

blocks/pdf-viewer/pdf-viewer.css, blocks/pdf-viewer/pdf-viewer.js
Fix #491 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/products/catalog
- After: https://491-fix-pdf-fullscreen--mammotome--hlxsites.hlx.page/us/en/products/catalog
=> fix: PDF fullscreen not supported on iOS

blocks/columns/columns.css, blocks/footer/footer.css, blocks/header/header.css, styles/styles.css
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/dj-test/en/
- After: https://521-general-refresh-styles--mammotome--hlxsites.hlx.page/dj-test/en/
=> feat: general styles (WIP)

scripts/delayed.js, scripts/scripts.js
Fix GTM Setup
Test URLs:
- After: https://fix-gtm-setup--mammotome--hlxsites.hlx.page/us/en/
=> fix: move GTM to delayed and set cookie mode

scripts/delayed.js, scripts/scripts.js
Test URLs:
- After: https://reduce-gtm-load-time--mammotome--hlxsites.hlx.page/us/en/
=> fix: reduce GTM loading time

blocks/hero-carousel/hero-carousel.css
Fix #523 
Test URLs:
- After: https://523-header-image-cut-off--mammotome--hlxsites.hlx.page/us/en/
=> fix header image cut off

blocks/hero-carousel/hero-carousel.css
This reverts commit 8b315bd8e89c717ff22dd9af9ec2c742ebc891be.
As per [customer request](https://adobe-dx-support.slack.com/archives/C04T6MD0TDM/p1691508023846759?thread_ts=1691436502.716899&cid=C04T6MD0TDM) this change should be reverted.
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/dj-test/en/
- After: https://revert-header-image-fix--mammotome--hlxsites.hlx.page/dj-test/en/
=> Revert "fix header image cut off (#526)"

blocks/hero-carousel/hero-carousel.css, blocks/hero-carousel/hero-carousel.js, scripts/lib-carousel.js
REVIEW ON MOBILE (TOUCH)
Fix #533
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/jc-test/en/hero-carousel
- After: https://533-improve-carousel-vertical-scrolling--mammotome--hlxsites.hlx.page/jc-test/en/hero-carousel
=> improve scroll behaviour when touch scroll vertically

blocks/form/form.js
Fix #511 #501
Test URLs:
- After: https://error--mammotome--hlxsites.hlx.page/us/en/contact/
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- After: https://error--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
- After: https://error--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
- After: https://error--mammotome--hlxsites.hlx.page/us/en/about-us/innovat …
=> fix: Implement gec, localised form error

blocks/form/form.js
https://adobe-dx-support.slack.com/archives/C04T6MD0TDM/p1692138366664939 
Test URLs:
- After: https://semicolom--mammotome--hlxsites.hlx.page/us/en/contact/
=> fix: Add semicolon instead of comma

blocks/product-carousel/product-carousel.css, blocks/product-carousel/product-carousel.js
Fix #549
Test URLs:
- After: https://549-fix-product-carousel-overflow-issue--mammotome--hlxsites.hlx.page/us/en/
=> fix link overflow of hidde products

blocks/columns/columns.css, docs/blocks/columns.md
Fix #551 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/a-culture-of-continuous-improvement
- After: https://551-variable-font-weights-column-blocks--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/a-culture-of-continuous-improvement
=> Add option for bigger font-weight for columns block

blocks/hero-carousel/hero-carousel.css, styles/styles.css
Fix #562 
Test URLs:
- After: https://562-hero-carousel-bullet-improvements--mammotome--hlxsites.hlx.page/us/en/
=> improved style for Hero Carousel navigation dots

scripts/lib-history-section.js, scripts/scripts.js, styles/styles.css
Fix #544, history script import fix
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.live/us/en/about-us/our-history
- After: https://script-import-fix--mammotome--sselvara.hlx.live/us/en/about-us/our-history
=> Script import optimization

scripts/scripts.js
Added Fathom Analytics
Fix #569 
Test URLs:
- After: https://569-fathom-analytics--mammotome--hlxsites.hlx.page/us/en/
=> Fathom Analytics

scripts/delayed.js, scripts/scripts.js
Fix #571 
Test URLs:
- After: https://571-fathom-delayed--mammotome--hlxsites.hlx.page/us/en/
=> 571 SEO fathom delayed

blocks/columns/columns.css
Fix #573 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/
- After: https://573-bug-content-size-subscript--mammotome--hlxsites.hlx.page/us/en/about-us/
=> 573-bug-content-size-subscript

.github/pull_request_template.md, README.md, blocks/pdf-viewer/pdf-viewer.js, scripts/lib-franklin.js, scripts/scripts.js
Test URLs:
- Before: https://main--mammotome--hlxsites.aem.page/us/en/
- After: https://helix5--mammotome--hlxsites.aem.page/us/en/
=> Rewrite links to work with helix5

blocks/onetrust-ccpa/onetrust-ccpa.css, blocks/onetrust-ccpa/onetrust-ccpa.js, blocks/onetrust-cookie/onetrust-cookie.css, blocks/onetrust-cookie/onetrust-cookie.js, blocks/onetrust-privacy/onetrust-privacy.css, blocks/onetrust-privacy/onetrust-privacy.js, scripts/lib-franklin.js
Test URLs:
- Before: https://main--mammotome--hlxsites.aem.page/us/en/
- After: https://585-implement-onetrust-pages--mammotome--hlxsites.aem.page/us/en/
=> 585-implement-onetrust-pages
