hlxsites/mammotome

head.html
scripts/scripts.js
site.webmanifest

reducing amount of icon definitions and re-introduction data placeholder so browsers still see the icon even if loaded lazily.
also introducing android site manifest
Test URLs:
- After: https://simplify-favicons--mammotome--hlxsites.hlx.page/en/

fix: simplify favicons

---

blocks/header/header.css
blocks/header/header.js
blocks/tab-navigation/tab-navigation.js
scripts/lib-franklin.js

Add active link highlighting for MultiNav (typical product pages) and refactor tab-navigation.js → move setActiveLink function to franklin lib
Fix #147 
Test URLs:
After: 
- https://147-highlight-active-page-in-top-nav--mammotome--hlxsites.hlx.page/en/
- https://147-highlight-active-page-in-top-nav--mammotome--hlxsites.hlx.page/en/patient-resources/understanding-biopsy-results

fix: active nav highlighting

---

blocks/collapsible/collapsible.css

Collapsible moves into hero
Fix #194
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/patient-resources/faq-about-the-devices
- After: https://194-collpsible-moves-inot-hero--mammotome--hlxsites.hlx.page/en/patient-resources/faq-about-the-devices

fix: overlap with hero block + added 'narrow' style

---

blocks/columns/columns.css

Fix #196 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/portfolios/stereotactic
- After: https://196-hero-hides-parts-of-h2--mammotome--hlxsites.hlx.page/en/portfolios/stereotactic

fix for hero hides headlines

---

blocks/header/header.css

Please make sure to configure your mobile browser appropriately before testing (e.g. Safari should use the desktop browser).
Fix #234 
Test URLs:
- After: https://234-fix--mammotome--hlxsites.hlx.page/us/en/

fix: hide overflow-x for enclosing ul

---

blocks/columns/columns.css
styles/styles.css

Reverts hlxsites/mammotome#320 
Introduced bug in Columns padding: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars

Revert "fix: image padding, link color invert"

---

blocks/columns/columns.js

Fix #317 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/
- After: https://317-enforce-paragraph-in-text-only-columns--mammotome--hlxsites.hlx.page/us/en/about-us/

317 - force wrapping the content of text-only columns in a paragraph

---

blocks/product-reference/product-reference.js

When a `product-reference` is used in a nested sub-path like e.g.: `/it/it/products/mammotome-revolve/mammotome-revolve-u-s` it ends up reference the wrong url because it only goes one level up. In the example, it ends-up being `/it/it/products/product-support/mammotome-revolve`. Instead, it should always go directly under `/<country>/<lang>/product-support`
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/it/it/products/mammotome-revolve/mammotome-revolve-u-s
- After: https://fix-product-reference--mammotome--hlxsites.hlx.page/it/it/products/mammotome-revolve/mammotome-revolve-u-s

Fix product reference target when in nested subpage

---

blocks/product-support/product-support.js
scripts/lib-franklin.js

The detection for adding icons to pdf download links assumes that tagNames are lowercase - which must not be the case. Furthermore, in the case of at least the product-support, the links where not wrapped in a `button-container`div.
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support
- After: https://fix-pdf-button--mammotome--hlxsites.hlx.page/us/en/product-support/mammotome-revolve-support

Fix the pdf download links in the product support.

---

blocks/ifus/ifus.css

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/ifu-index
- After: https://ifus-align--mammotome--hlxsites.hlx.page/us/en/ifu-index

fix: ifus align should only target headers below ifus block

---

blocks/pdf-viewer/pdf-viewer.css

PDF document link is erroneously shown for PDF viewer
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/products/catalog
- After: https://fix-hide-pdf-viewer-link--mammotome--hlxsites.hlx.page/us/en/products/catalog

fix: hide pdf link

---

scripts/lib-franklin.js

That is a problem because it wants a button-container class on the parent of the pdf link. In the corner case where it adds a button-container class to the parent, it does that after it looked whether the parent has that class. Doing it the other way around, it works.
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence
- After: https://fix-decorate-buttons--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence

fix: decorateButtons tries to detect pdfs before it adds button container

---

styles/styles.css

On Safari (both on the desktop as well as on mobil) there is a sub pixel issue that can cause the arc at the bottom of the page to not align completely with the section above it - causing a sub pixel gap where the background shines through. That looks like an arbitrary line e.g.:
The reason is that we use percentage for the margins and if those end-up as not a whole number that sub-pixel will be where the arc box starts - having a small visual gap where the background comes through. 
As there is no good way to round those margins in the css (at least none that I could fine), the simplest solution seems to be to just position the arc svg relative and pull it up one negative pixel. 
Test URLs:
- After: …

fix: subpixel issue in safari creates line between arc and section.

---

blocks/ifus/ifus.css

Fix #310 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/ifu-index
- After: https://310-eifu-buttons--mammotome--hlxsites.hlx.page/us/en/ifu-index

fix: IFU result buttons text uppercase

---

blocks/form/form.js

Currently the forms block doesn't match form URLs ending in anything else than ".json", e.g. ".json?sheet=de" - this is needed for multi-language support
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/kontakt
- After: https://forms-support-language-sheets--mammotome--hlxsites.hlx.page/de/de/kontakt

fix: also support parameters in form link

---

blocks/form/form.js

Re-add what another PR overwrote by mistake.
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/kontakt
- After: https://forms-support-language-sheets-2--mammotome--hlxsites.hlx.page/de/de/kontakt

fix: re-add language support (overwritten by other p)

---

blocks/product-list/product-list.js
blocks/product-reference/product-reference.js

The actual issue in #427 was that there was no translation placeholder in place for the contact and product-support urls in the us/en version. After adding those, it worked - however, there is a bug in the product reference block that in one case is prepending the country and language to that url which makes it point to an invalid url if the product-support url is set via the placeholders. This PR fixes that.
Fix #427 
Test URLs:
- After: https://427-product-support-ref--mammotome--hlxsites.hlx.page/us/en/products/breast-biopsy-markers/

fix: product support reference url

---

blocks/columns/columns.css

Fix #422 
Test URLs:
URLs without the margin:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence
- After: https://422-columns-margin--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/clinical-evidence
URLs that needed the margin:
- Before:  https://main--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization
- After: https://422-columns-margin--mammotome--hlxsites.hlx.page/us/en/portfolios/magnetic-lesion-localization

Columns: Margin 8% not needed everywhere

---

scripts/scripts.js
templates/legacy/script.js
templates/refresh/script.js

Introduce ability to specify template in page metadata. If no template is specified, the default "legacy" template is applied.
Templates are located in the `./templates/<template-name>/` folder and must feature a `styles.css` and `script.js` file.
Added empty legacy and refresh templates.
Fix #493 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/drafts/
- After: https://493-introduce-templating-mechanism--mammotome--hlxsites.hlx.page/us/en/drafts/

feat: introduce templating mechanism

---

scripts/scripts.js

Fix background image optimization: use resize observer to select correct breakpoints irrespective of Device Pixel Ratio (DPR) as before.
Test URLs:
- After: 
- https://blurry-background-image--mammotome--hlxsites.hlx.page/us/en/
- https://blurry-background-image--mammotome--hlxsites.hlx.page/dj-test/en/

fix: optimize background image for breakpoints

---

blocks/header/header.css

Fix #566 
Test URLs:
- After: https://566-search-result-links-hidden--mammotome--hlxsites.hlx.page/us/en/

fix search results links in mobile view

---

blocks/prev-next/prev-next.js

Fix #575 
Test URLs:
- After: https://575-bug-text-prev-next--mammotome--hlxsites.hlx.page/us/en/
- After: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-launches-lumimark-press-release

575 fix: Update prev-next.js using HTML instead of Text

---

blocks/onetrust-ccpa/onetrust-ccpa.js
blocks/onetrust-cookie/onetrust-cookie.js
blocks/onetrust-privacy/onetrust-privacy.js

Fix #588 
Test URLs:
- Before: https://main--mammotome--hlxsites.aem.page/us/en/
- After: https://588-add-onetrust-entity--mammotome--hlxsites.aem.page/us/en/

588-add-onetrust-entity
